// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoriesLibrary.Data;

namespace StoriesLibrary.Migrations
{
    [DbContext(typeof(StoriesContext))]
    [Migration("20210313090609_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("StoriesLibrary.Shared.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mp3FileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Eva Artés",
                            Category = "terror",
                            PublishedDate = new DateTime(2021, 2, 28, 13, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Los ángulos tienen dientes"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Raquel Sastre",
                            Category = "novela",
                            PublishedDate = new DateTime(2021, 2, 28, 14, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "La gasolinera"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Andrés López",
                            Category = "terror",
                            PublishedDate = new DateTime(2021, 2, 28, 15, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Dejad que los niños se acerquen a mí"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Lucía Castillo",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 16, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "El vuelo al fin del mundo"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Diego de Salazar",
                            Category = "novela",
                            PublishedDate = new DateTime(2021, 2, 28, 17, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "El tocador de la abuela"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Daniela Rubio",
                            Category = "novela",
                            PublishedDate = new DateTime(2021, 2, 28, 18, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Las cerillas mojadas no sirven para nada"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ricardo Allen",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 19, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Sacando las castañas del fuego"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Núria Azanza",
                            Category = "novela histórica",
                            PublishedDate = new DateTime(2021, 2, 28, 20, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Los árboles invisibles"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Blanca Romero",
                            Category = "novela",
                            PublishedDate = new DateTime(2021, 2, 28, 21, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Dirección prohibida"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Alfonso Tirado",
                            Category = "romántica",
                            PublishedDate = new DateTime(2021, 2, 28, 22, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "El olor de las margaritas"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Alejandro Carbonell",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 23, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Planetas sin vida"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Ignacio Aguado",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 0, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "La vacuna"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Cristóbal Lafuente",
                            Category = "Thriller",
                            PublishedDate = new DateTime(2021, 2, 28, 1, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "El master"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Eduardo Préscoli",
                            Category = "romántica",
                            PublishedDate = new DateTime(2021, 2, 28, 2, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "El desorden de tu ausencia"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Gloria Onrubia",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 3, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Los amigos que fuimos"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Elena Carrión",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 4, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Saltando charcos"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Jesús Palomo",
                            Category = "literatura",
                            PublishedDate = new DateTime(2021, 2, 28, 5, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Las garras del hambre"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Daniel Martín",
                            Category = "Thriller",
                            PublishedDate = new DateTime(2021, 2, 28, 5, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "El barco de papel"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Rosa Ramos",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 6, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Los gatos también ladran"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Roberto Masip",
                            Category = "novela",
                            PublishedDate = new DateTime(2021, 2, 28, 7, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "Durmiendo"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Juan María Martín",
                            Category = "ciencia ficción",
                            PublishedDate = new DateTime(2021, 2, 28, 8, 22, 51, 0, DateTimeKind.Unspecified),
                            Text = "Línea 1\r\nLínea 2",
                            Title = "La mirada vacía"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
